### PR TITLE
Clean endpoint registration

### PR DESCRIPTION
**Pull request by gquintard**

### CODE REVIEW

**Comment by Dridi** [comment]
The test suite consistently fails with this pull request on my system, whereas current master passes.

Also, instead of keeping the names `callback_t` and `http_register_url`, please use `http_cb_f` and `http_register_path`. This will avoid temp "2" names and increase naming consistency.

**Comment by gquintard** [comment]
Fair enough, test suite consistently failed on both on my machine so I didn't think twice about it.

**Comment by Dridi** [comment]
I did the rename thing like this:

```
git checkout origin/pull/181
git checkout -b tmp
git filter-branch --tree-filter 'git sed -e s/callback2_t/http_cb_f/g' master..tmp
git filter-branch --tree-filter 'git sed -e s/http_register_url2/http_register_path/g' master..tmp
```

Now that it's passing on my machine, reviewing&amending.

**Comment by Dridi** [comment]
Merged as ca0a474...8d2ea97

**Pull request closed without merging**
