### PR TITLE
Fix memory leaks in vparams code

### PR DESCRIPTION
**Pull request by Dridi**
Still not complete, it took me time to find out why the test suite was inconsistently failing (no more space in `/tmp`).

For now, it's only a fix for the first leak reported in #168, I will have a look at the other on Monday.

### CODE REVIEW

**Comment by Dridi** [comment]
The tests are failing but if I remember correctly it's been the case for a while on Travis CI. At least in the build 188, the relevant passes in both jobs: `PASS: json.sh`.

**Comment by fgsch** [comment]
Tests have been failing for a bit. Something changed in the travis infrastructure.
We need to sort it out but as long as it passes in Jenkins we should be OK.

**Comment by Dridi** [comment]
More commits including a *controversial* drop of Varnish 3 support for parameters.

**Comment by Dridi** [comment]
Timed out, I pushed to the master branch.

**Pull request merged**
