### PR TITLE
Free pointers to avoid memory leaks

### LINKED ISSUE #167: memory leaks in vbackends code
vbackends_show_json() will leak ptr, out1 and out2

### PR DESCRIPTION
**Pull request by aondio**
Fixes #167

### CODE REVIEW

**Comment by fgsch** [comment]
This looks OK.

I'd suggest to pass the vsb struct around to avoid asprintf but this can be done in a separate commit.

**Comment by Dridi** [comment]
Arianna, you have commits from @hugocruz in there, please rebase onto the current master to have only your three commits. Also the test suite is failing on travis-ci, is the test suite stable?

**Comment by hugocruz** [comment]
I'm looking into the travis issue. 
Everything works both locally and in jenkins. It might be some dependency that travis updated. 
I could try re-run an older passing build, but I don't see any restart build button as they document. Permissions?

**Comment by Dridi** [comment]
@hugocruz I also don't see the restart feature, so either permissions, repo configuration or maybe it doesn't work with VM builds.

**Comment by hugocruz** [comment]
More info [here](https://docs.travis-ci.com/user/common-build-problems/#My-tests-broke-but-were-working-yesterday)

**Comment by hugocruz** [comment]
So I manage to re-run an old build that was running in travis, turns out it fails now: https://travis-ci.org/varnish/vagent2/jobs/124620473

So it is something in Travis that was updated and messes up the tests. 

Let's not care about travis for a while. :)

**Comment by aondio** [comment]
a1d27be0b85ff43b29f0676eccc13354ec57ffaf

**Pull request closed without merging**
