### PR TITLE
Bumping up the version. Editing the changelog for 4.0.2

### PR DESCRIPTION
**Pull request by hugocruz**

### CODE REVIEW

**Comment by Dridi** [comment]
Please push a4bda0b first, and we'll look at the results on jenkins for the debian build. If it's good, push the bumping commit and go for the release!

**Comment by hugocruz** [comment]
Yes, doing that first :)

**Comment by Dridi** [comment]
I've pushed ab370a6 and checked the deb packages produced by the jenkins build, they look fine. So then I pushed 51fa623 so you should now be able to proceed with the release!

**Comment by hugocruz** [comment]
Still need to check the el ones

**Pull request closed without merging**
